from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict

from app.modules.organizations.constants.organization_status import (
    OrganizationStatus,
)
from app.modules.organizations.constants.organization_type import (
    OrganizationType,
)


class OrganizationBaseSchema(BaseModel):
    """
    Base schema shared across create, update and response models.
    """

    name: str
    organization_type: OrganizationType

    email: str | None = None
    phone: str | None = None
    website: str | None = None

    timezone: str | None = None

    logo_url: str | None = None
    primary_color: str | None = None
    secondary_color: str | None = None

    description: str | None = None
    tax_id: str | None = None

    is_active: bool = True


class OrganizationCreateSchema(OrganizationBaseSchema):
    """
    Schema used when creating a new organization.

    Slug and status are generated by the system.
    """
    pass


class OrganizationUpdateSchema(BaseModel):
    """
    Schema used for partial updates.

    Every field is optional to support PATCH requests.
    """

    name: str | None = None
    organization_type: OrganizationType | None = None

    email: str | None = None
    phone: str | None = None
    website: str | None = None

    timezone: str | None = None

    logo_url: str | None = None
    primary_color: str | None = None
    secondary_color: str | None = None

    description: str | None = None
    tax_id: str | None = None

    status: OrganizationStatus | None = None
    is_active: bool | None = None


class OrganizationResponseSchema(OrganizationBaseSchema):
    """
    Schema returned to API consumers.
    """

    id: UUID
    slug: str
    status: OrganizationStatus

    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(
        from_attributes=True,
    )