"""create providers table

Revision ID: 025c7340e73a
Revises: 9ba22e88ff76
Create Date: 2026-05-24 00:08:04.321925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025c7340e73a'
down_revision: Union[str, None] = '9ba22e88ff76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('speciality', sa.String(length=120), nullable=True),
    sa.Column('license_number', sa.String(length=120), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_providers_provider_type'), 'providers', ['provider_type'], unique=False)
    op.create_index(op.f('ix_providers_speciality'), 'providers', ['speciality'], unique=False)
    op.create_index(op.f('ix_providers_user_id'), 'providers', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_user_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_speciality'), table_name='providers')
    op.drop_index(op.f('ix_providers_provider_type'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
