"""add sales members table

Revision ID: 0bbbe7eb9d4e
Revises: 409c56bf5d68
Create Date: 2026-08-01 14:59:24.906056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbbe7eb9d4e'
down_revision: Union[str, None] = '409c56bf5d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sales_organization_id', sa.UUID(), nullable=False),
    sa.Column('sales_team_id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('SALES_ADMINISTRATOR', 'REGIONAL_MANAGER', 'SALES_MANAGER', 'ACCOUNT_MANAGER', 'SALES_EXECUTIVE', 'CUSTOMER_SUCCESS_EXECUTIVE', 'FINANCE_EXECUTIVE', name='sales_member_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='sales_member_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sales_organization_id'], ['sales_organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_team_id'], ['sales_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sales_organization_id', name='uq_sales_member_per_organization')
    )
    op.create_index(op.f('ix_sales_members_sales_organization_id'), 'sales_members', ['sales_organization_id'], unique=False)
    op.create_index(op.f('ix_sales_members_sales_team_id'), 'sales_members', ['sales_team_id'], unique=False)
    op.create_index(op.f('ix_sales_members_territory_id'), 'sales_members', ['territory_id'], unique=False)
    op.create_index(op.f('ix_sales_members_user_id'), 'sales_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_members_user_id'), table_name='sales_members')
    op.drop_index(op.f('ix_sales_members_territory_id'), table_name='sales_members')
    op.drop_index(op.f('ix_sales_members_sales_team_id'), table_name='sales_members')
    op.drop_index(op.f('ix_sales_members_sales_organization_id'), table_name='sales_members')
    op.drop_table('sales_members')
    # ### end Alembic commands ###
