"""add google auth fields

Revision ID: 2533fae00e5b
Revises: ed0dd862e597
Create Date: 2026-06-02 23:21:20.341736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2533fae00e5b'
down_revision: Union[str, None] = 'ed0dd862e597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column(
        "users",
        sa.Column("auth_provider",sa.String(length=50),nullable=False,server_default="local"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
