"""add territories table

Revision ID: 409c56bf5d68
Revises: 9d30709f80f3
Create Date: 2026-08-01 00:31:45.939748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409c56bf5d68'
down_revision: Union[str, None] = '9d30709f80f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('territories',
    sa.Column('sales_organization_id', sa.UUID(), nullable=False),
    sa.Column('parent_territory_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Enum('COUNTRY', 'REGION', 'STATE', 'CITY', 'ZONE', name='territory_level'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='territory_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_territory_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_organization_id'], ['sales_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_organization_id', 'code', name='uq_territory_code_per_sales_org'),
    sa.UniqueConstraint('sales_organization_id', 'parent_territory_id', 'name', name='uq_territory_name_per_parent')
    )
    op.create_index(op.f('ix_territories_parent_territory_id'), 'territories', ['parent_territory_id'], unique=False)
    op.create_index(op.f('ix_territories_sales_organization_id'), 'territories', ['sales_organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_territories_sales_organization_id'), table_name='territories')
    op.drop_index(op.f('ix_territories_parent_territory_id'), table_name='territories')
    op.drop_table('territories')
    # ### end Alembic commands ###
