"""update auth schema

Revision ID: 708e6f14dd4f
Revises: 19e64de242dd
Create Date: 2026-05-20 23:24:59.544314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708e6f14dd4f'
down_revision: Union[str, None] = '19e64de242dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('user_sessions', sa.Column('refresh_token_hash', sa.String(length=255), nullable=False))
    op.add_column('user_sessions', sa.Column('device_name', sa.String(length=255), nullable=True))
    op.add_column('user_sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('user_sessions', 'refresh_token')
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'mfa_enabled')
    op.add_column('user_sessions', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_sessions', 'updated_at')
    op.drop_column('user_sessions', 'created_at')
    op.drop_column('user_sessions', 'device_name')
    op.drop_column('user_sessions', 'refresh_token_hash')
    op.drop_column('roles', 'description')
    op.drop_table('user_profiles')
    op.drop_table('role_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
