"""add organization sales accounts table

Revision ID: 84a3309f8c88
Revises: 0bbbe7eb9d4e
Create Date: 2026-08-01 18:51:22.270804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a3309f8c88'
down_revision: Union[str, None] = '0bbbe7eb9d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_sales_accounts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sales_organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_sales_member_id', sa.UUID(), nullable=False),
    sa.Column('account_owner_sales_member_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.Enum('DIRECT', 'RESELLER', 'ENTERPRISE', 'PARTNER', 'INTERNAL', name='organization_sales_account_type'), nullable=False),
    sa.Column('status', sa.Enum('PROSPECT', 'ONBOARDING', 'ACTIVE', 'SUSPENDED', 'CHURNED', name='organization_sales_account_status'), nullable=False),
    sa.Column('customer_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_owner_sales_member_id'], ['sales_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_sales_member_id'], ['sales_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_organization_id'], ['sales_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_organization_sales_account')
    )
    op.create_index(op.f('ix_organization_sales_accounts_account_number'), 'organization_sales_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_organization_sales_accounts_account_owner_sales_member_id'), 'organization_sales_accounts', ['account_owner_sales_member_id'], unique=False)
    op.create_index(op.f('ix_organization_sales_accounts_created_by_sales_member_id'), 'organization_sales_accounts', ['created_by_sales_member_id'], unique=False)
    op.create_index(op.f('ix_organization_sales_accounts_organization_id'), 'organization_sales_accounts', ['organization_id'], unique=True)
    op.create_index(op.f('ix_organization_sales_accounts_sales_organization_id'), 'organization_sales_accounts', ['sales_organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_sales_accounts_sales_organization_id'), table_name='organization_sales_accounts')
    op.drop_index(op.f('ix_organization_sales_accounts_organization_id'), table_name='organization_sales_accounts')
    op.drop_index(op.f('ix_organization_sales_accounts_created_by_sales_member_id'), table_name='organization_sales_accounts')
    op.drop_index(op.f('ix_organization_sales_accounts_account_owner_sales_member_id'), table_name='organization_sales_accounts')
    op.drop_index(op.f('ix_organization_sales_accounts_account_number'), table_name='organization_sales_accounts')
    op.drop_table('organization_sales_accounts')
    # ### end Alembic commands ###
