"""add appointment provider schedule index

Revision ID: 880e06236712
Revises: 291e7276742f
Create Date: 2026-05-24 23:18:14.042686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880e06236712'
down_revision: Union[str, None] = '291e7276742f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_appointments_provider_schedule', 'appointments', ['provider_id', 'scheduled_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_provider_schedule', table_name='appointments')
    # ### end Alembic commands ###
