"""create sales organization and sales team tables

Revision ID: 9d30709f80f3
Revises: 3551757dc3b3
Create Date: 2026-07-30 23:24:51.597039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d30709f80f3'
down_revision: Union[str, None] = '3551757dc3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'ARCHIVED', name='sales_organization_status'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_organizations_name'), 'sales_organizations', ['name'], unique=True)
    op.create_index(op.f('ix_sales_organizations_slug'), 'sales_organizations', ['slug'], unique=True)
    op.create_table('sales_teams',
    sa.Column('sales_organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('team_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='sales_team_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sales_organization_id'], ['sales_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_organization_id', 'name', name='uq_sales_team_name_per_organization'),
    sa.UniqueConstraint('sales_organization_id', 'team_code', name='uq_sales_team_code_per_organization')
    )
    op.create_index(op.f('ix_sales_teams_sales_organization_id'), 'sales_teams', ['sales_organization_id'], unique=False)
    op.drop_constraint('uq_org_user_membership', 'organization_memberships', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_org_user_membership', 'organization_memberships', ['organization_id', 'user_id'])
    op.drop_index(op.f('ix_sales_teams_sales_organization_id'), table_name='sales_teams')
    op.drop_table('sales_teams')
    op.drop_index(op.f('ix_sales_organizations_slug'), table_name='sales_organizations')
    op.drop_index(op.f('ix_sales_organizations_name'), table_name='sales_organizations')
    op.drop_table('sales_organizations')
    # ### end Alembic commands ###
