"""update provider constraints and activation

Revision ID: ff01ae3fe2dd
Revises: 025c7340e73a
Create Date: 2026-05-24 19:30:13.088468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff01ae3fe2dd'
down_revision: Union[str, None] = '025c7340e73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers',sa.Column('is_active', sa.Boolean(),nullable=False,server_default=sa.true(),))
    op.drop_index('ix_providers_user_id', table_name='providers')
    op.create_unique_constraint(None, 'providers', ['user_id'])
    op.drop_constraint('providers_user_id_fkey', 'providers', type_='foreignkey')
    op.create_foreign_key(None, 'providers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.create_foreign_key('providers_user_id_fkey', 'providers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'providers', type_='unique')
    op.create_index('ix_providers_user_id', 'providers', ['user_id'], unique=True)
    op.drop_column('providers', 'is_active')
    # ### end Alembic commands ###
