from enum import Enum


class AuditAction(str, Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    VIEW = "VIEW"
    EXPORT = "EXPORT"
    DOWNLOAD = "DOWNLOAD"

    TOKEN_REFRESH = "TOKEN_REFRESH"

    OTP_GENERATED = "OTP_GENERATED"
    OTP_VERIFIED = "OTP_VERIFIED"
    OTP_VERIFICATION_FAILED = "OTP_VERIFICATION_FAILED"
    
    RESEND = "RESEND"
    ACCEPT = "ACCEPT"
    DECLINE = "DECLINE"
    CANCEL = "CANCEL"


class AuditResource(str, Enum):
    USER = "USER"
    PATIENT = "PATIENT"
    APPOINTMENT = "APPOINTMENT"
    CONSULTATION = "CONSULTATION"
    LAB = "LAB"
    PRESCRIPTION = "PRESCRIPTION"
    ROLE = "ROLE"
    PERMISSION = "PERMISSION"
    FILE = "FILE"
    PAYMENT = "PAYMENT"
    SUBSCRIPTION = "SUBSCRIPTION"

    ORGANIZATION = "ORGANIZATION"
    ORGANIZATION_MEMBERSHIP = "ORGANIZATION_MEMBERSHIP"
    ORGANIZATION_INVITATION = "ORGANIZATION_INVITATION"
    SALES_ORGANIZATION = "SALES_ORGANIZATION"
    SALES_TEAM = "SALES_TEAM"
    TERRITORY = "TERRITORY"
    SALES_MEMBER = "SALES_MEMBER"

    OTP = "OTP"