from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict

from app.modules.sales.constants.sales_organization_enums import (
    SalesOrganizationStatus,
)


class SalesOrganizationBaseSchema(BaseModel):
    """
    Base schema shared across create, update and response models.
    """

    name: str

    email: str | None = None
    phone: str | None = None
    website: str | None = None

    country: str | None = None
    timezone: str | None = None

    logo_url: str | None = None
    primary_color: str | None = None
    secondary_color: str | None = None

    description: str | None = None

    is_active: bool = True


class SalesOrganizationCreateSchema(
    SalesOrganizationBaseSchema,
):
    """
    Schema used when creating a new Sales Organization.

    Slug and status are generated by the system.
    """

    pass


class SalesOrganizationUpdateSchema(BaseModel):
    """
    Schema used for partial updates.

    Every field is optional to support PATCH requests.
    """

    name: str | None = None

    email: str | None = None
    phone: str | None = None
    website: str | None = None

    country: str | None = None
    timezone: str | None = None

    logo_url: str | None = None
    primary_color: str | None = None
    secondary_color: str | None = None

    description: str | None = None

    status: SalesOrganizationStatus | None = None

    is_active: bool | None = None


class SalesOrganizationResponseSchema(
    SalesOrganizationBaseSchema,
):
    """
    Schema returned to API consumers.
    """

    id: UUID

    slug: str

    status: SalesOrganizationStatus

    created_at: datetime

    updated_at: datetime

    model_config = ConfigDict(
        from_attributes=True,
    )