from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict

from app.modules.sales.constants.sales_enums import (
    SalesTeamStatus,
)


class SalesTeamBaseSchema(BaseModel):
    """
    Base schema shared across create, update and response models.
    """

    name: str

    team_code: str

    description: str | None = None

    is_active: bool = True


class SalesTeamCreateSchema(SalesTeamBaseSchema):
    """
    Schema used when creating a new Sales Team.

    Status is generated by the system.
    """

    sales_organization_id: UUID


class SalesTeamUpdateSchema(BaseModel):
    """
    Schema used for partial updates.

    Every field is optional to support PUT/PATCH style updates.
    """

    name: str | None = None

    team_code: str | None = None

    description: str | None = None

    status: SalesTeamStatus | None = None

    is_active: bool | None = None


class SalesTeamResponseSchema(SalesTeamBaseSchema):
    """
    Schema returned to API consumers.
    """

    id: UUID

    sales_organization_id: UUID

    status: SalesTeamStatus

    created_at: datetime

    updated_at: datetime

    model_config = ConfigDict(
        from_attributes=True,
    )